name: Tests

on:
  push:
    branches:
      - main
      - jest
  pull_request:
    branches:
      - main
      - jest

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['12', '14', '16']
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update npm
        run: npm i -g npm
        if: ${{ matrix.node-version <= 14 }}
      - name: Install Packages
        run: npm ci
      - name: Build Package
        run: npm run build
      - name: Run Tests
        run: npm run test
